---
title: "hak2_clean"
author: "Grigory Gladkov"
date: "2025-08-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

df.exp <- read_csv("LE_2017_2021.csv")  %>% 
  filter(!Region %in% "Republic of Kazakhstan") %>% 
  mutate(Region = case_when(
      Region == "Akmola" ~ "Акмолинская",
      Region == "Aktobe" ~ "Актюбинская",
      Region == "Almaty" ~ "Алматинская",
      Region == "Atyrau" ~ "Атырауская",
      Region == "West Kazakhstan" ~ "Западно-Казахстанская",
      Region == "Jambyl" ~ "Жамбылская",
      Region == "Karaganda" ~ "Карагандинская",
      Region == "Kostanay" ~ "Костанайская",
      Region == "Kyzylorda" ~ "Кызылординская",
      Region == "Mangystau" ~ "Мангистауская",
      Region == "Pavlodar" ~ "Павлодарская",
      Region == "North Kazakhstan" ~ "Северо-Казахстанская",
      Region == "Turkistan" ~ "Туркестанская",
      Region == "East Kazakhstan" ~ "Восточно-Казахстанская",
      Region == "Astana city" ~ "г.Нур-Султан",
      Region == "Almaty city" ~ "г.Алматы", 
      .default = Region)) %>% 
  rename("Область" = "Region") %>% 
  pivot_longer(-Область, names_to = "Year", values_to = "LifeExpectancy") %>% 
  mutate(Year = as.double(Year))

le.for.kaz <- read_csv("LE_2017_2021.csv") %>% 
  filter(Region == "Republic of Kazakhstan") %>% 
  column_to_rownames("Region") %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column("Year") %>% 
  mutate(Year = as.numeric(Year))

exch.df <- read_excel("Dollar.xlsx") %>%
  select(-Валюта) %>% 
  pivot_longer(-Год, names_to = "Month", values_to = "ExchangeRate") %>% 
    mutate(Month = case_when(
      Month == "Январь" ~ "1",
      Month == "Февраль" ~ "2",
      Month == "Март" ~ "3",
      Month == "Апрель" ~ "4",
      Month == "Май" ~ "5",
      Month == "Июнь" ~ "6",
      Month == "Июль" ~ "7",
      Month == "Август" ~ "8",
      Month == "Сентябрь" ~ "9",
      Month == "Октябрь" ~ "10",
      Month == "Ноябрь" ~ "11",
      Month == "Декабрь" ~ "12",
      .default = Month)) %>% 
  mutate(Month = as.numeric(Month))

inf.df <- read_csv("inflation.csv") %>% # select(-Валюта) %>% 
      pivot_longer(-Год, names_to = "Month", values_to = "Inflation") %>% 
      mutate(Month = case_when(
      Month == "Январь" ~ "1",
      Month == "Февраль" ~ "2",
      Month == "Март" ~ "3",
      Month == "Апрель" ~ "4",
      Month == "Май" ~ "5",
      Month == "Июнь" ~ "6",
      Month == "Июль" ~ "7",
      Month == "Август" ~ "8",
      Month == "Сентябрь" ~ "9",
      Month == "Октябрь" ~ "10",
      Month == "Ноябрь" ~ "11",
      Month == "Декабрь" ~ "12",
      .default = Month)) %>% 
  mutate(Month = as.numeric(Month))


```


```{r}

df.new <- df %>% 
  dplyr::rename("WellBeing" = "q10a. В целом как бы Вы оценили свое здоровье в настоящее время?",
         "Year" = "Год", 
         "Month" = "Месяц",
         "Loc" = "Тип местности",
         "Education" = "Уровень образования",
         "Sex" = "Пол",
         "Age" = "Возраст",
         "Marriage" = "Семейное положение",
         "Work" = "Положение в занятости",
         "Income" = "q47. Считаете ли Вы себя материально обеспеченным человеком?",
         "Environment" = "q8. Оцените, пожалуйста, экологическую ситуацию в Вашем населенном пункте",
         "FamilySize" = "Размер домохозяйства, человек",
         "Children" = "Число детей до 18 лет",
         "TrustState" = "q9.1. Оцените, пожалуйста, качество медицинских услуг в государственных медицинских учреждениях (поликлиники, больницы) в Казахстане",
         "TrustPrivate" = "q9.2. Оцените, пожалуйста, качество медицинских услуг в  частных клиниках в Казахстане"
         ) %>%
    mutate(Education = case_when(
      Education == "Нет начального" ~ "Basic",
      Education == "Начальное (1-4 классы)" ~ "Basic",
      Education == "Основное среднее (5-9 классы)" ~ "Basic",
      Education == "Среднее общее (10-11 классы)" ~ "Basic",
      Education == "Начальное профессиональное (на базе среднего общего)" ~ "Middle",
      Education == "Среднее профессиональное (колледж, училище)" ~ "Middle",
      Education == "Незаконченное высшее" ~ "Advanced",
      Education == "Высшее" ~ "Advanced",
      Education == "Послевузовское" ~ "Advanced",
    )) %>% 
    mutate(Work = case_when(
      Work == "Я пенсионер" ~ "allowance",
      Work == "Я не работаю по состоянию здоровья / по инвалидности" ~ "allowance",
      Work == "Я безработный (-ая)" ~ "allowance",
      Work == "Я студент" ~ "allowance",
      Work == "Я работаю по найму в госорганизации" ~ "state",
      Work == "Я работаю по найму в частной организации" ~ "private",
      Work == "Я собственник бизнеса" ~ "self-employed",
      Work == "Я собственник бизнеса" ~ "self-employed",
      Work == "Я домохозяйка/домохозяин" ~ "self-employed",
      Work == "Я самозанятый" ~ "self-employed",
      Work == "Я работаю в своем личном подсобном хозяйстве" ~ "self-employed",
      .default = as.character(Work)
    )) %>% 
  mutate(WellBeing = as.factor(WellBeing)) %>% 
  mutate(Work = as.factor(Work)) %>% 
  mutate(Income = as.factor(Income)) %>% 
  mutate(Envinroment = as.factor(Environment)) %>% 
  mutate(FamilySize = as.factor(FamilySize)) %>% 
  mutate(Children = as.factor(Children)) %>% 
  mutate(TrustState = as.factor(TrustState)) %>% 
  mutate(TrustPrivate = as.factor(TrustPrivate)) %>% 
  mutate(Children = factor(Children, levels = c("нет детей до 18 лет", "1", "2", "3", "4 и более"))) %>%
  mutate(WellBeing = factor(WellBeing, levels = c("Ужасное", "Плохое", "Удовлетворительное", "Хорошее", "Прекрасное"))) %>%
  mutate(Income = factor(Income, levels = c("Нет", "Скорее нет", "Скорее да", "Да"))) %>%
  mutate(Envinroment = factor(Environment, levels = c("Плохая", "Удовлетворительная", "Хорошая"))) %>%
  mutate(TrustState = factor(TrustState, levels = c("Плохое", "Удовлетворительное", "Хорошее"))) %>%
  mutate(TrustPrivate = factor(TrustPrivate, levels = c("Плохое", "Удовлетворительное", "Хорошее"))) %>%
  mutate(Education = as.factor(Education)) %>% 
  mutate(Education=fct_relevel(Education,c("Basic", "Middle", "Advanced"))) %>% 
  mutate(WellBeing = as.numeric(WellBeing)) %>%
  mutate(TrustState = as.numeric(TrustState)) %>%
  mutate(TrustPrivate = as.numeric(TrustPrivate)) %>%
  left_join(df.exp) %>% 
  dplyr::rename("Region" = "Область") %>% 
  left_join(le.for.kaz) %>%  
  left_join(exch.df) %>%  
  left_join(inf.df) %>%  
  mutate(LifeExpectancy = if_else(LifeExpectancy > `Republic of Kazakhstan`, 0, 1))
  
df.new2 <- df.new %>% 
  # select(Year, Month) %>% 
  mutate(YearHappens = ifelse(Year == 2019 & Month %in% c(10, 11, 12), 1, 0)) %>% 
  mutate(YearCovid = ifelse(Year > 2020 & Month > 1, 1, 0)) %>% 
  mutate(QuartCovid = ifelse(Year == 2020 & Month %in% c(1, 2, 3), 1, 0))


```


```{r}

ols.wb.qq <- lm(WellBeing ~ QuartCovid*LifeExpectancy + Age + Marriage + Education + Loc + Income + Environment + Work + Sex + ExchangeRate + Inflation + YearCovid, data = df.new2)
ols.wb.yh <- lm(WellBeing ~ YearHappens*LifeExpectancy + Age + Marriage + Education + Loc + Income + Environment + Work + Sex + ExchangeRate + Inflation + YearCovid, data = df.new2)
ols.tp.yh <- lm(TrustPrivate ~ YearHappens*LifeExpectancy + Age + Marriage + Education + Loc + Income + Environment + Work + Sex + ExchangeRate + Inflation + YearCovid, data = df.new2)
ols.ts.yh <- lm(TrustState ~ YearHappens*LifeExpectancy + Age + Marriage + Education + Loc + Income + Environment + Work + Sex + ExchangeRate + Inflation + YearCovid, data = df.new2)
ols.tp.qq <- lm(TrustPrivate ~ QuartCovid*LifeExpectancy + Age + Marriage + Education + Loc + Income + Environment + Work + Sex + ExchangeRate + Inflation + YearCovid, data = df.new2)
ols.ts.qq <- lm(TrustState ~ QuartCovid*LifeExpectancy + Age + Marriage + Education + Loc + Income + Environment + Work + Sex + ExchangeRate + Inflation + YearCovid, data = df.new2)

```


```{r}

summary(ols.tp.qq)
summary(ols.wb.yh)
summary(ols.ts.yh)
summary(ols.ts.qq)
summary(ols.tp.yh)
summary(ols.tp.qq)

```



```{r}

coefs <- summary(ols.wb.yh)$coef
conf_int <- confint(ols.wb.yh)

results <- data.frame(
  term = rownames(coefs),
  estimate = coefs[, "Estimate"],
  lower = conf_int[, 1],
  upper = conf_int[, 2]
)

results <- results %>%
  filter(term %in% c("YearHappens","QuartCovid", "LifeExpectancy", "ExchangeRate", "Inflation"))
  
p.wb.yh <- ggplot(results, aes(x = term, y = estimate, ymin = lower, ymax = upper)) +
  geom_pointrange() +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  coord_flip() + 
  labs(
    title = "Well-being ~ Health Care reform",
    x = "Predictors",
    y = "SE"
  ) +
  theme_minimal()


coefs <- summary(ols.wb.qq)$coef
conf_int <- confint(ols.wb.qq)

results <- data.frame(
  term = rownames(coefs),
  estimate = coefs[, "Estimate"],
  lower = conf_int[, 1],
  upper = conf_int[, 2]
)

results <- results %>%
  filter(term %in% c("YearHappens","QuartCovid", "LifeExpectancy", "ExchangeRate", "Inflation"))
  
p.wb.qq <- ggplot(results, aes(x = term, y = estimate, ymin = lower, ymax = upper)) +
  geom_pointrange() +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  coord_flip() +  # Делаем горизонтальный "forest plot"
  labs(
    title = "Well-being ~ Covid",
    x = "Predictors",
    y = "SE"
  ) +
  theme_minimal()


coefs <- summary(ols.tp.yh)$coef
conf_int <- confint(ols.tp.yh)

results <- data.frame(
  term = rownames(coefs),
  estimate = coefs[, "Estimate"],
  lower = conf_int[, 1],
  upper = conf_int[, 2]
)


results <- results %>%
  filter(term %in% c("YearHappens","QuartCovid", "LifeExpectancy", "ExchangeRate", "Inflation"))
  
p.tp.yh <- ggplot(results, aes(x = term, y = estimate, ymin = lower, ymax = upper)) +
  geom_pointrange() +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  coord_flip() +  # Делаем горизонтальный "forest plot"
  labs(
    title = "Private Medicine ~ Health Care reform",
    x = "Predictors",
    y = "SE"
  ) +
  theme_minimal()

coefs <- summary(ols.tp.qq)$coef
conf_int <- confint(ols.tp.qq)

results <- data.frame(
  term = rownames(coefs),
  estimate = coefs[, "Estimate"],
  lower = conf_int[, 1],
  upper = conf_int[, 2]
)


results <- results %>%
  filter(term %in% c("YearHappens","QuartCovid", "LifeExpectancy", "ExchangeRate", "Inflation"))
  
p.tp.qq <- ggplot(results, aes(x = term, y = estimate, ymin = lower, ymax = upper)) +
  geom_pointrange() +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  coord_flip() +  # Делаем горизонтальный "forest plot"
  labs(
    title = "Private Medicine ~ Covid",
    x = "Predictors",
    y = "SE"
  ) +
  theme_minimal()

coefs <- summary(ols.ts.yh)$coef
conf_int <- confint(ols.ts.yh)

results <- data.frame(
  term = rownames(coefs),
  estimate = coefs[, "Estimate"],
  lower = conf_int[, 1],
  upper = conf_int[, 2]
)


results <- results %>%
  filter(term %in% c("YearHappens","QuartCovid", "LifeExpectancy", "ExchangeRate", "Inflation"))
  
p.ts.yh <- ggplot(results, aes(x = term, y = estimate, ymin = lower, ymax = upper)) +
  geom_pointrange() +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  coord_flip() +  
  labs(
    title = "Public Medicine ~ Health Care reform",
    x = "Predictors",
    y = "SE"
  ) +
  theme_minimal()

coefs <- summary(ols.ts.qq)$coef
conf_int <- confint(ols.ts.qq)

results <- data.frame(
  term = rownames(coefs),
  estimate = coefs[, "Estimate"],
  lower = conf_int[, 1],
  upper = conf_int[, 2]
)


results <- results %>%
  filter(term %in% c("YearHappens","QuartCovid", "LifeExpectancy", "ExchangeRate", "Inflation"))
  
p.ts.qq <- ggplot(results, aes(x = term, y = estimate, ymin = lower, ymax = upper)) +
  geom_pointrange() +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  coord_flip() +  
  labs(
    title = "Public Medicine ~ Covid",
    x = "Predictors",
    y = "SE"
  ) +
  theme_minimal()


ggarrange(p.wb.yh, p.wb.qq, p.tp.yh, p.tp.qq, p.ts.yh, p.ts.qq, nrow = 2, ncol = 3)


```





